"""Setup http sources table

Revision ID: 6a9cfbcfe36c
Revises: 64d1c82f82f5
Create Date: 2025-11-21 10:22:00.991228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9cfbcfe36c'
down_revision: Union[str, Sequence[str], None] = '64d1c82f82f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ctl_http_sources',
    sa.Column('source_key', sa.String(), nullable=False, comment='Source key'),
    sa.Column('source_url', sa.String(), nullable=True, comment='Source URL'),
    sa.Column('source_method', sa.String(), nullable=True, comment='Source HTTP method'),
    sa.Column('source_params', sa.JSON(), nullable=True, comment='Source HTTP parameters'),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.drop_table('ctl_file_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ctl_file_sources',
    sa.Column('file_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='File key'),
    sa.Column('file_description', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='File description'),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='File import enabled'),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='File type'),
    sa.PrimaryKeyConstraint('file_key', name=op.f('ctl_file_sources_pkey'))
    )
    op.drop_table('ctl_http_sources')
    # ### end Alembic commands ###
