"""Setup filesources table

Revision ID: e8ba08948a48
Revises: 6a9cfbcfe36c
Create Date: 2025-11-21 10:27:04.435318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ba08948a48'
down_revision: Union[str, Sequence[str], None] = '6a9cfbcfe36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ctl_file_sources',
    sa.Column('file_key', sa.String(length=50), nullable=False, comment='File key'),
    sa.Column('file_description', sa.String(length=100), nullable=True, comment='File description'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='File import enabled'),
    sa.Column('file_type', sa.Enum('CSV', 'EXCEL', 'JSON', 'PARQUET', 'XML', name='sysfiletype'), nullable=True, comment='File type'),
    sa.PrimaryKeyConstraint('file_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ctl_file_sources')
    # ### end Alembic commands ###
